name: Deploy
on:
  push:
    branches:
      # - master
      - "*"
  pull_request:
    branches:
      - master

jobs:
  Stage1:
    name: Stage 1
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm run build --if-present
      - run: npm run deploy
      - name: Determine If Master
        run: |
          release_branch=$(test "${{ github.ref }}" = refs/heads/master -o "${{ github.ref }}" = refs/heads/2.0/master -o "${{ github.ref }}" = refs/heads/3.0/master && echo true || echo false)
          echo "Is this a release branch? ${release_branch}"
          echo "SHOULD_TAG=${release_branch}" >> $GITHUB_ENV
      - name: Create a GitHub release
        if: ${{ success() && env.SHOULD_TAG=='true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.SEMVER_ESCAPED }}
