name: Deploy
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  Stage1:
    name: Stage 1
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - run: npm install
      - run: npm run build --if-present
      - name: Publish Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
      - name: Determine If Main
        run: |
          release_branch=$(test "${{ github.ref }}" = refs/heads/main && echo true || echo false)
          echo "Is this a release branch? ${release_branch}"
          echo "SHOULD_TAG=${release_branch}" >> $GITHUB_ENV
      - name: Create a GitHub release
        if: ${{ success() && env.SHOULD_TAG=='true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.SEMVER_ESCAPED }}
