name: Pull Request
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
jobs:
  PullRequest:
    name: Pull Request
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - run: npm install
      - run: npm run build --if-present
